MODEL:
  TRANSFORMER_TYPE: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  DIRECT: 1
  PREFIX: True
  TEXT_PROMPT: 1
  INVERSE: True
  DA: True

  PRETRAIN_PATH_T: '/root/cloud-ssd/IDEA-main/PTH/ViT-B-16.pt'
  ATT_DROP_RATE: 0.0
  DROP_OUT: 0.0
  DROP_PATH: 0.1
  FORWARD: 'old'
  FROZEN: False
  ID_LOSS_TYPE: 'softmax'
  ID_LOSS_WEIGHT: 0.25
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  METRIC_LOSS_TYPE: 'triplet'
  NECK: 'bnneck'
  NO_MARGIN: True
  SIE_CAMERA: True
  SIE_COE: 1.0
  SIE_VIEW: False
  TRIPLET_LOSS_WEIGHT: 1.0


  CDA:
    N_HEADS: 1
    N_HEAD_CHANNELS: 512
    N_GROUPS: 1
    STRIDE: 2
    WINDOW_SIZE: [5, 5]
    Q_SIZE: [8, 16]
    STRIDE_BLOCK: [4, 4]
    KSIZE: 5
    OFFSET_RANGE_FACTOR: 25


    WAVE_NUM_GROUPS: 4
    WAVE_ALPHA: 0.08
    WAVE_TIME_STEP: 0.9
    WAVE_GLOBAL_ALPHA: 0.04
    WAVE_GLOBAL_TIME_STEP: 0.7


    ENABLE_GLOBAL_WPO: True
    VISUALIZE_WEIGHTS: False

INPUT:
  SIZE_TRAIN: [128, 256]
  SIZE_TEST: [128, 256]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 8
  NUM_WORKERS: 14

DATASETS:
  NAMES: ('MSVR310')
  ROOT_DIR: '/root/cloud-ssd/IDEA-main/datasets'

SOLVER:
  BASE_LR: 0.00035
  WARMUP_ITERS: 10
  MAX_EPOCHS: 50
  OPTIMIZER_NAME: 'Adam'
  IMS_PER_BATCH: 64
  LOG_PERIOD: 1
  EVAL_PERIOD: 1

TEST:
  IMS_PER_BATCH: 128
  WEIGHT: ''
  MISS: 'nothing'

OUTPUT_DIR: './IDEA_MSVR310'